---
- name: List disks on Windows machine with size in GB
  hosts: windows
  gather_facts: no
  tasks:
    - name: Get disk information and convert size to GB
      win_command: |
        powershell Get-WmiObject -Class Win32_DiskDrive | 
        Select-Object DeviceID, Model, @{Name="Size(GB)";Expression={[math]::round($_.Size / 1GB, 2)}}, MediaType
      register: disk_info

    - name: Display disk information
      debug:
        var: disk_info.stdout_lines
