---
- hosts: all
  tasks:
    - name: Get disk facts
      win_disk_facts:

    - name: Show all disk details
      debug:
        msg: 
          - "Disk {{ loop.index }} - Size: {{ item.size | filesizeformat(true) }} ({{ (item.size/1024|pow(3))|round|int }} GiB)"
          - "System Disk: {{ item.system_disk | default('No') }}"
      loop: "{{ ansible_facts.disks }}"
      loop_control:
        index_var: loop_index

    - name: Convert all disks into various formats
      debug:
        msg: 
          - "Disk {{ loop.index }}:"
          - "  Size in GiB: {{ (item.size/1024|pow(3))|round|int }}"
          - "  Human-readable Size: {{ item.size | filesizeformat(true) }}"
          - "  System Disk: {{ item.system_disk | default('No') }}"
      loop: "{{ ansible_facts.disks }}"
