---
- name: List disks on Windows machine
  hosts: all
  gather_facts: yes
  tasks:
    - name: Get disk information
      win_command: "powershell Get-WmiObject -Class Win32_DiskDrive | Select-Object DeviceID, Model, Size, MediaType"
      register: disk_info

    - name: Display disk information
      debug:
        var: disk_info.stdout_lines
