---
- hosts: all
  gather_facts: no
  tasks:
    - name: Get disk facts
      win_disk_facts:

    - name: List all disks
      debug:
        msg: 
          - "Disk {{ loop.index }}:"
          - "  Device ID: {{ item.device_id }}"
          - "  Size: {{ item.size | filesizeformat(true) }}"
          - "  System Disk: {{ 'Yes' if item.system_disk else 'No' }}"
          - "  Model: {{ item.model }}"
          - "  Serial Number: {{ item.serial_number }}"
      loop: "{{ ansible_facts.disks }}"
      when: ansible_facts.disks is defined
