---
- hosts: all
  tasks:
    - name: Get disk facts
      win_disk_facts:

    - name: List all disks
      debug:
        msg: 
          - "Disk {{ (item.1 | int) + 1 }}:"
          - "  Device ID: {{ item.0.device_id }}"
          - "  Size: {{ item.0.size | filesizeformat(true) }}"
          - "  System Disk: {{ 'Yes' if item.0.system_disk else 'No' }}"
          - "  Model: {{ item.0.model }}"
          - "  Serial Number: {{ item.0.serial_number }}"
      loop: "{{ ansible_facts.disks | zip_longest(range(ansible_facts.disks | length)) | list }}"
      when: ansible_facts.disks is defined
