---
- name: Essential Ubuntu Configuration
  hosts: all
  tasks:
    # Install some common packages
    - name: Install essential packages
      apt:
        name: 
          - unzip
          - git
          - vim
          - python3-pip
        state: present

    # Create a new user with sudo privileges
    - name: Add a new user with sudo privileges
      user:
        name: morphdemo
        groups: sudo
        append: yes
        state: present
        create_home: yes
        shell: /bin/bash
