---
- name: Download files to a custom directory on Windows
  hosts: all
  vars:
    morpheusresult: "{{ morpheus['results']['customDir'] }}"
  tasks:
    - name: Debug morpheus result
      debug:
        msg: "Result is {{ morpheus['results']['customDir'] }}"

    - name: Setting fact to morpheus result from previous task
      set_fact:
        resultstrip: "{{ morpheusresult | replace('\n', '') }}"

    - debug:
        var: resultstrip

    - name: Ensure target directory exists
      win_file:
        path: "C:\{{ resultstrip }}"
        state: directory

    - name: Download sample file 1
      win_get_url:
        url: https://www.learningcontainer.com/wp-content/uploads/2020/04/sample-text-file.txt
        dest: "C:\{{ resultstrip }}\\sample1.txt"

    - name: Download sample file 2
      win_get_url:
        url: https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf
        dest: "C:\{{ resultstrip }}\\dummy.pdf"
