---
- name: Search all critical and security updates
  hosts: all
  tasks:
    - debug:
        msg: "Result is {{ morpheus['results']['installMsi'] }}"
    - name: Search Windows Update
      win_updates:
        category_names:
         - CriticalUpdates
         - SecurityUpdates
        state: searched
        log_path: C:\ansible_wu.txt
      when: "{{ morpheus['results']['installMsi'] }}" == "Else"
