---
- name: Search all critical and security updates
  hosts: all
  tasks:
    - name: Search Windows Update
      win_updates:
        category_names:
         - CriticalUpdates
         - SecurityUpdates
        state: searched
        log_path: C:\ansible_wu.txt
      when: "{{ morpheus['results']['installMsi'] }}" == "Else"
    - name: Getting value
      set_fact:
        resultvalue: "{{ morpheus['results']['installMsi'] }}"
    - debug: var=resultvalue

