---
- name: Search all critical and security updates
  hosts: all
  vars:
    morpheusresult: "{{ morpheus['results']['installMsi'] }}"
  tasks:
    - debug:
        msg: "Result is {{morpheus['results']['installMsi']}}"
    - name: Setting fact to morpheus result from previous task
      set_fact:
        resultstrip: "{{ morpheusresult | replace('\n', '') }}"
    - debug:
        var: resultstrip
    - name: Search Windows Update
      win_updates:
        category_names:
         - CriticalUpdates
         - SecurityUpdates
        state: searched
        log_path: C:\ansible_wu.txt
      when: resultstrip == "Else"

